import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'
import enagerd from './enagerd'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'pages',
        path: '',
        title: 'PAGES',
        translateKey: 'nav.pages',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [],
    },
    {
        key: 'gestionProcesos',
        path: '',
        title: 'DGP',
        translateKey: 'nav.gestionProcesos',
        icon: 'file',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'gestionProcesos.lluviasAvisoMeteorologico',
                path: '/gestion-procesos/lluviasAvisoMeteorologico',
                title: 'LAM',
                tooltip: 'Lluvias Aviso Meteorológico',
                translateKey: 'nav.gestionProcesos.lluviasAvisoMeteorologico',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'gestionProcesos.lluviasAvisoMeteorologico.estatico',
                        path: '/gestion-procesos/lluviasAvisoMeteorologico/estatico',
                        title: 'Modelo Estático',
                        translateKey: 'nav.gestionProcesos.lluviasAvisoMeteorologico.estatico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'gestionProcesos.lluviasAvisoMeteorologico.dinamico',
                        path: '/gestion-procesos/lluviasAvisoMeteorologico/dinamico',
                        title: 'Modelo Dinamico',
                        translateKey: 'nav.gestionProcesos.lluviasAvisoMeteorologico.dinamico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    }
                ],
            },
            {
                key: 'gestionProcesos.lluviasAvisoTrimestral',
                path: '/gestion-procesos/lluviasAvisoTrimestral',
                title: 'LAT',
                tooltip: 'Lluvias Aviso Trimestral',
                translateKey: 'nav.gestionProcesos.lluviasAvisoTrimestral',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'gestionProcesos.lluviasAvisoTrimestral.estatico',
                        path: '/gestion-procesos/lluviasAvisoTrimestral/estatico',
                        title: 'Modelo Estático',
                        translateKey: 'nav.gestionProcesos.lluviasAvisoTrimestral.estatico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],

                    },
                    {
                        key: 'gestionProcesos.lluviasAvisoTrimestral.dinamico',
                        path: '/gestion-procesos/lluviasAvisoTrimestral/dinamico',
                        title: 'Modelo Dinámico',
                        translateKey: 'nav.gestionProcesos.lluviasAvisoTrimestral.dinamico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],

                    }
                ],
            },
            {
                key: 'gestionProcesos.lluviasInformacionClimatica',
                path: '/gestion-procesos/lluviasInformacionClimatica',
                title: 'LIC',
                tooltip: 'Lluvias Información Climática',
                translateKey: 'nav.gestionProcesos.lluviasInformacionClimatica',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'gestionProcesos.lluviasInformacionClimatica.estatico',
                        path: '/gestion-procesos/lluviasInformacionClimatica/estatico',
                        title: 'Modelo Estático',
                        translateKey: 'nav.gestionProcesos.lluviasInformacionClimatica.estatico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'gestionProcesos.lluviasInformacionClimatica.dinamico',
                        path: '/gestion-procesos/lluviasInformacionClimatica/dinamico',
                        title: 'Modelo Dinámico',
                        translateKey: 'nav.gestionProcesos.lluviasInformacionClimatica.dinamico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    }
                ],
            },
            {
                key: 'gestionProcesos.bajasTempAvisoMeteorologico',
                path: '/gestion-procesos/bajasTempAvisoMeteorologico',
                title: 'BTAM',
                tooltip: 'Bajas Temp Aviso Meteorológico',
                translateKey: 'nav.gestionProcesos.bajasTempAvisoMeteorologico',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'gestionProcesos.bajasTempAvisoMeteorologico.estatico',
                        path: '/gestion-procesos/bajasTempAvisoMeteorologico/estatico',
                        title: 'Modelo Estático',
                        translateKey: 'nav.gestionProcesos.bajasTempAvisoMeteorologico.estatico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'gestionProcesos.bajasTempAvisoMeteorologico.dinamico',
                        path: '/gestion-procesos/bajasTempAvisoMeteorologico/dinamico',
                        title: 'Modelo Dinámico',
                        translateKey: 'nav.gestionProcesos.bajasTempAvisoMeteorologico.dinamico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    }
                ],
            },
            {
                key: 'gestionProcesos.bajasTempAvisoTrimestral',
                path: '/gestion-procesos/bajasTempAvisoTrimestral',
                title: 'BTAT',
                tooltip: 'Bajas Temp Aviso Trimestral',
                translateKey: 'nav.gestionProcesos.bajasTempAvisoTrimestral',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'gestionProcesos.bajasTempAvisoTrimestral.estatico',
                        path: '/gestion-procesos/bajasTempAvisoTrimestral/estatico',
                        title: 'Modelo Estático',
                        translateKey: 'nav.gestionProcesos.bajasTempAvisoTrimestral.estatico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'gestionProcesos.bajasTempAvisoTrimestral.dinamico',
                        path: '/gestion-procesos/bajasTempAvisoTrimestral/dinamico',
                        title: 'Modelo Dinámico',
                        translateKey: 'nav.gestionProcesos.bajasTempAvisoTrimestral.dinamico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },

                ],
            },
            {
                key: 'gestionProcesos.bajasTempInformacionClimatica',
                path: '/gestion-procesos/bajasTempInformacionClimatica',
                title: 'BTIC',
                tooltip: 'Bajas Temp Información Climática',
                translateKey:
                    'nav.gestionProcesos.bajasTempInformacionClimatica',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'gestionProcesos.bajasTempInformacionClimatica.estatico',
                        path: '/gestion-procesos/bajasTempInformacionClimatica/estatico',
                        title: 'Modelo Estático',
                        translateKey: 'nav.gestionProcesos.bajasTempInformacionClimatica.estatico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'gestionProcesos.bajasTempInformacionClimatica.dinamico',
                        path: '/gestion-procesos/bajasTempInformacionClimatica/dinamico',
                        title: 'Modelo Dinámico',
                        translateKey: 'nav.gestionProcesos.bajasTempInformacionClimatica.dinamico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    }
                ],
            },
            {
                key: 'gestionProcesos.incendiosForestalesNacional',
                path: '/gestion-procesos/incendiosForestalesNacional',
                title: 'IFN',
                tooltip: 'Incendios Forestales Nac',
                translateKey: 'nav.gestionProcesos.incendiosForestalesNacional',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'gestionProcesos.incendiosForestalesNacional.estatico',
                        path: '/gestion-procesos/incendiosForestalesNacional/estatico',
                        title: 'Modelo Estático',
                        translateKey: 'nav.gestionProcesos.incendiosForestalesNacional.estatico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'gestionProcesos.incendiosForestalesNacional.dinamico',
                        path: '/gestion-procesos/incendiosForestalesNacional/dinamico',
                        title: 'Modelo Dinámico',
                        translateKey: 'nav.gestionProcesos.incendiosForestalesNacional.dinamico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },

                ],
            },
            {
                key: 'gestionProcesos.incendiosForestalesRegional',
                path: '/gestion-procesos/incendiosForestalesRegional',
                title: 'IFR',
                tooltip: 'Incendios Forestales Reg',
                translateKey: 'nav.gestionProcesos.incendiosForestalesRegional',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'gestionProcesos.incendiosForestalesRegional.estatico',
                        path: '/gestion-procesos/incendiosForestalesRegional/estatico',
                        title: 'Modelo Estático',
                        translateKey: 'nav.gestionProcesos.incendiosForestalesRegional.estatico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'gestionProcesos.incendiosForestalesRegional.dinamico',
                        path: '/gestion-procesos/incendiosForestalesRegional/dinamico',
                        title: 'Modelo Dinámico',
                        translateKey: 'nav.gestionProcesos.incendiosForestalesRegional.dinamico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    }
                ],
            },
            {
                key: 'gestionProcesos.sismosTsunamiNacional',
                path: '/gestion-procesos/sismosTsunamiNacional',
                title: 'STN',
                tooltip: 'Sismos Tsunami Nac',
                translateKey: 'nav.gestionProcesos.sismosTsunamiNacional',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'gestionProcesos.sismosTsunamiNacional.estatico',
                        path: '/gestion-procesos/sismosTsunamiNacional/estatico',
                        title: 'Modelo Estático',
                        translateKey: 'nav.gestionProcesos.sismosTsunamiNacional.estatico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'gestionProcesos.sismosTsunamiNacional.dinamico',
                        path: '/gestion-procesos/sismosTsunamiNacional/dinamico',
                        title: 'Modelo Dinámico',
                        translateKey: 'nav.gestionProcesos.sismosTsunamiNacional.dinamico',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    }
                ],
            },
            /*
            {
                key: 'gestionProcesos.sismosTsunamiOtrosAmbitos',
                path: '/gestion-procesos/sismosTsunamiOtrosAmbitos',
                title: 'Sismos Tsunami Otros Ámbitos',
                translateKey: 'nav.gestionProcesos.sismosTsunamiOtrosAmbitos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sequiasNacional',
                path: '/gestion-procesos/sequiasNacional',
                title: 'Sequías Nacional',
                translateKey: 'nav.gestionProcesos.sequiasNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sequiasDepartamental',
                path: '/gestion-procesos/sequiasDepartamental',
                title: 'Sequías Dep',
                translateKey: 'nav.gestionProcesos.sequiasDepartamental',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.volcanesNacional',
                path: '/gestion-procesos/volcanesNacional',
                title: 'Volcanes Nac',
                translateKey: 'nav.gestionProcesos.volcanesNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            */
        ],
    },
    // {
    //     key: 'fortalecimiento',
    //     path: '',
    //     title: 'DIFAT',
    //     translateKey: 'nav.fortalecimiento',
    //     icon: 'collapseMenu',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    // subMenu: [
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Resumen Instrumento Niv Nac',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Resumen Dpto Asist Tec Fortalec',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Fort Cap Cursos Bas y Espec',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Evaluadores de Riesgo Acred',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Fort Cap y Ambitos',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Riesgo por Fen Naturales',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Otras Asistencias Tec Nacional',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Concurso Buenas Practicas',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Concurso Buenas Practicas',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Fases del PPRD Nacional',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Instrumentos Especialistas Nacional',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Sesiones Espec PPRD Nivel Nac',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Entidades Asist Esp PPRD Nacional',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    // ],
    // },
    {
        key: 'dimse',
        path: '',
        title: 'DIFAT',
        translateKey: 'nav.dimse',
        icon: 'chart',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'fortalecimiento.resumenInstrumentoNivNac',
                path: '/fortalecimiento/resumenInstrumentoNivNac',
                title: 'Instrumentos a Nivel Nacional',
                translateKey: 'nav.fortalecimiento.resumenInstrumentoNivNac',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.fortCapYAmbitos',
                path: '/fortalecimiento/fortCapYAmbitos',
                title: 'Programa Anual de Actividades',
                translateKey: 'nav.fortalecimiento.fortCapYAmbitos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.concursoBuenasPracticas',
                path: '/fortalecimiento/concursoBuenasPracticas',
                title: 'Fortalecimiento Capacidades (CB-CE)',
                translateKey: 'nav.fortalecimiento.concursoBuenasPracticas',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.fortCapCursosBasYEspec',
                path: '/fortalecimiento/fortCapCursosBasYEspec',
                title: 'PPRRD por Regiones y Años',
                translateKey: 'nav.fortalecimiento.fortCapCursosBasYEspec',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.fasesDelPprdNacional',
                path: '/fortalecimiento/fasesDelPprdNacional',
                title: 'Evaluadores de Riesgo Acreditados',
                translateKey: 'nav.fortalecimiento.fasesDelPprdNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.otrasAsistenciasTecNacional',
                path: '/fortalecimiento/otrasAsistenciasTecNacional',
                title: 'Planes Estratégicos y Reconstrucción',
                translateKey: 'nav.fortalecimiento.otrasAsistenciasTecNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.riesgoPorFenNaturales',
                path: '/fortalecimiento/riesgoPorFenNaturales',
                title: 'Plan Educación Comunitaria - REP',
                translateKey: 'nav.fortalecimiento.riesgoPorFenNaturales',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.evaluadoresDeRiesgoAcred',
                path: '/fortalecimiento/evaluadoresDeRiesgoAcred',
                title: 'Evaluadores de Riesgo por Regiones Años',
                translateKey: 'nav.fortalecimiento.evaluadoresDeRiesgoAcred',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.pprdNivelNacional',
                path: '/fortalecimiento/pprdNivelNacional',
                title: 'PPRRD - Entidades Asistidas',
                translateKey: 'nav.fortalecimiento.pprdNivelNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.resumenDptoAsistTecFortalec',
                path: '/fortalecimiento/resumenDptoAsistTecFortalec',
                title: 'ATFC por Regiones y Años',
                translateKey: 'nav.fortalecimiento.resumenDptoAsistTecFortalec',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            /*
            {
                key: 'fortalecimiento.instrumentosEspecialistasNacional',
                path: '/fortalecimiento/instrumentosEspecialistasNacional',
                title: 'Concurso Buenas Prácticas',
                translateKey:
                    'nav.fortalecimiento.instrumentosEspecialistasNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.sesionesEspecPprdNivelNac',
                path: '/fortalecimiento/sesionesEspecPprdNivelNac',
                title: 'Aula Virtual',
                translateKey: 'nav.fortalecimiento.sesionesEspecPprdNivelNac',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.entidadesAsistEspPprdNacional',
                path: '/fortalecimiento/entidadesAsistEspPprdNacional',
                title: 'Fases del PPRD Especialista',
                translateKey:
                    'nav.fortalecimiento.entidadesAsistEspPprdNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            */
        ],
    },
    {
        key: 'monitoreo',
        path: '',
        title: 'DIMSE',
        translateKey: 'nav.monitoreo',
        icon: 'monitor',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'monitoreo.monitoreo',
                path: '/monitoreo/monitoreo',
                title: 'Monitoreo',
                translateKey: 'nav.monitoreo.monitoreo',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'monitoreo.seguimiento',
                path: '/monitoreo/seguimiento',
                title: 'Seguimiento',
                translateKey: 'nav.monitoreo.seguimiento',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'monitoreo.supervision',
                path: '/monitoreo/supervision',
                title: 'Supervisión',
                translateKey: 'nav.monitoreo.supervision',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'monitoreo.evaluacion',
                path: '/monitoreo/evaluacion',
                title: 'Evaluación',
                translateKey: 'nav.monitoreo.evaluacion',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'monitoreo.directorioNacional',
                path: '/monitoreo/directorioNacional',
                title: 'Directorio Nacional',
                translateKey: 'nav.monitoreo.directorioNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            enagerd,
        ],
    },
]

export default navigationConfig
