import { NavigationTree } from '@/@types/navigation';
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

const navigationConfig: NavigationTree = {
    key: 'monitoreo.monitoreo',
    path: '/monitoreo/monitoreo',
    title: 'Reportes ejecucion',
    translateKey: 'nav.monitoreo.monitoreo',
    icon: '',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2025',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2024',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2023',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Esc. riesgo 2023',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2022',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución estudios inv 2022',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2021',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2020-2021',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2019',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
    ],
};
export default navigationConfig;
