import { NavigationTree } from '@/@types/navigation';
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

const navigationConfig: NavigationTree = {
    key: 'reportes.ejecucion',
    path: '/monitoreo/monitoreo',
    title: 'Reportes ejecución',
    translateKey: 'nav.reportes.ejecucion',
    icon: '',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
        {
            key: 'reportes.ejecucion.enagerd2025',
            path: 'https://dimse.cenepred.gob.pe/ejecucion_enagerd/2025/eje_ena_reporte3c.php',
            title: 'Ejecución Enagerd 2025',
            translateKey: 'nav.reportes.ejecucion.enagerd2025',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            isExternalLink: true,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2024',
            path: 'https://dimse.cenepred.gob.pe/ejecucion_enagerd/2024/eje_ena_reporte3c.php',
            title: 'Ejecución Enagerd 2024',
            translateKey: 'nav.reportes.ejecucion.enagerd2024',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            isExternalLink: true,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2023',
            path: 'https://dimse.cenepred.gob.pe/ejecucion_enagerd/2023/eje_ena_reporte3c.php',
            title: 'Ejecución Enagerd 2023',
            translateKey: 'nav.reportes.ejecucion.enagerd2023',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            isExternalLink: true,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.escenarioRiesgo2023',
            path: 'https://dimse.cenepred.gob.pe/visor_ejecucion/2022/129765/eje_reporte3c.php',
            title: 'Ejecución Esc. riesgo 2023',
            translateKey: 'nav.reportes.ejecucion.escenarioRiesgo2023',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            isExternalLink: true,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2022',
            path: 'https://dimse.cenepred.gob.pe/ejecucion_enagerd/2022/eje_ena_reporte3c.php',
            title: 'Ejecución Enagerd 2022',
            translateKey: 'nav.reportes.ejecucion.enagerd2022',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            isExternalLink: true,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.estudiosInv2022',
            path: 'https://dimse.cenepred.gob.pe/visor_ejecucion/2022/164779/eje_reporte3c.php',
            title: 'Ejecución estudios inv 2022',
            translateKey: 'nav.reportes.ejecucion.estudiosInv2022',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            isExternalLink: true,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2021',
            path: 'https://dimse.cenepred.gob.pe/ejecucion_enagerd/2021/eje_ena_reporte3c.php',
            title: 'Ejecución Enagerd 2021',
            translateKey: 'nav.reportes.ejecucion.enagerd2021',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            isExternalLink: true,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2020_2021',
            path: 'https://dimse.cenepred.gob.pe/simse/cenepred/enagerd20202021/REPORTE_ENAGERD_2020_2021.htm',
            title: 'Ejecución Enagerd 2020-2021',
            translateKey: 'nav.reportes.ejecucion.enagerd2020_2021',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            isExternalLink: true,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2019',
            path: 'https://dimse.cenepred.gob.pe/simse/cenepred/enagerd2019/REPORTE_ENAGERD_2019.htm',
            title: 'Ejecución Enagerd 2019',
            translateKey: 'nav.reportes.ejecucion.enagerd2019',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            isExternalLink: true,
            authority: [],
            subMenu: [],
        },
    ],
};
export default navigationConfig;
