import { NavigationTree } from '@/@types/navigation';
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

const navigationConfig: NavigationTree = {
    key: 'reportes.ejecucion',
    path: '/monitoreo/monitoreo',
    title: 'Reportes ejecución',
    translateKey: 'nav.reportes.ejecucion',
    icon: '',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
        {
            key: 'reportes.ejecucion.enagerd2025',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2025',
            translateKey: 'nav.reportes.ejecucion.enagerd2025',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2024',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2024',
            translateKey: 'nav.reportes.ejecucion.enagerd2024',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2023',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2023',
            translateKey: 'nav.reportes.ejecucion.enagerd2023',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.escenarioRiesgo2023',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Esc. riesgo 2023',
            translateKey: 'nav.reportes.ejecucion.escenarioRiesgo2023',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2022',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2022',
            translateKey: 'nav.reportes.ejecucion.enagerd2022',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.estudiosInv2022',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución estudios inv 2022',
            translateKey: 'nav.reportes.ejecucion.estudiosInv2022',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2021',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2021',
            translateKey: 'nav.reportes.ejecucion.enagerd2021',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2020_2021',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2020-2021',
            translateKey: 'nav.reportes.ejecucion.enagerd2020_2021',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
        {
            key: 'reportes.ejecucion.enagerd2019',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución Enagerd 2019',
            translateKey: 'nav.reportes.ejecucion.enagerd2019',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [],
        },
    ],
};
export default navigationConfig;
