import { NavigationTree } from '@/@types/navigation';
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

const navigationConfig: NavigationTree = {
    key: 'geo.visores',
    path: '/monitoreo/monitoreo',
    title: 'Geo Visores',
    translateKey: 'nav.geo.visores',
    icon: '',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
        {
            key: 'geo.visores.ejecucion',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución',
            translateKey: 'nav.geo.visores.ejecucion',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [
                {
                    key: 'geo.visores.ejecucion.enagerd2025',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2025',
                    translateKey: 'nav.geo.visores.ejecucion.enagerd2025',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.ejecucion.enagerd2024',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2024',
                    translateKey: 'nav.geo.visores.ejecucion.enagerd2024',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.ejecucion.enagerd2023',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2023',
                    translateKey: 'nav.geo.visores.ejecucion.enagerd2023',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.ejecucion.escenarioRiesgo2023',
                    path: '/monitoreo/monitoreo',
                    title: 'Esc. riesgo 2023',
                    translateKey: 'nav.geo.visores.ejecucion.escenarioRiesgo2023',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.ejecucion.enagerd2022',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2022',
                    translateKey: 'nav.geo.visores.ejecucion.enagerd2022',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.ejecucion.escenarioRiesgoPprrd2022',
                    path: '/monitoreo/monitoreo',
                    title: 'Esc. riesgo y PPRRD 2022',
                    translateKey: 'nav.geo.visores.ejecucion.escenarioRiesgoPprrd2022',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.ejecucion.estudiosInv2022',
                    path: '/monitoreo/monitoreo',
                    title: 'Estudios inv 2022',
                    translateKey: 'nav.geo.visores.ejecucion.estudiosInv2022',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.ejecucion.enagerd2021',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2021',
                    translateKey: 'nav.geo.visores.ejecucion.enagerd2021',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.ejecucion.enagerd2020_2021',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2020-2021',
                    translateKey: 'nav.geo.visores.ejecucion.enagerd2020_2021',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.ejecucion.enagerd2019',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2019',
                    translateKey: 'nav.geo.visores.ejecucion.enagerd2019',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
            ],
        },
        {
            key: 'geo.visores.indicadores',
            path: '/monitoreo/monitoreo',
            title: 'Indicadores',
            translateKey: 'nav.geo.visores.indicadores',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [
                {
                    key: 'geo.visores.indicadores.indicadorGrd2024',
                    path: '/monitoreo/monitoreo',
                    title: 'Indicador GRD 2024',
                    translateKey: 'nav.geo.visores.indicadores.indicadorGrd2024',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.indicadores.supervisionPprrd',
                    path: '/monitoreo/monitoreo',
                    title: 'Supervisión PPRRD',
                    translateKey: 'nav.geo.visores.indicadores.supervisionPprrd',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
            ],
        },
        {
            key: 'geo.visores.resultadosPonderados',
            path: '/monitoreo/monitoreo',
            title: 'Resultados ponderados',
            translateKey: 'nav.geo.visores.resultadosPonderados',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [
                {
                    key: 'geo.visores.resultadosPonderados.enagerd2024',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2024',
                    translateKey: 'nav.geo.visores.resultadosPonderados.enagerd2024',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.resultadosPonderados.enagerd2020_2021',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2020-2021',
                    translateKey: 'nav.geo.visores.resultadosPonderados.enagerd2020_2021',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.resultadosPonderados.enagerd2019',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2019',
                    translateKey: 'nav.geo.visores.resultadosPonderados.enagerd2019',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.resultadosPonderados.enagerd2018',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2018',
                    translateKey: 'nav.geo.visores.resultadosPonderados.enagerd2018',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'geo.visores.resultadosPonderados.enagerd2017',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2017',
                    translateKey: 'nav.geo.visores.resultadosPonderados.enagerd2017',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
            ],
        },
    ],
};
export default navigationConfig;
