import { NavigationTree } from '@/@types/navigation';
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

const navigationConfig: NavigationTree = {
    key: 'monitoreo.monitoreo',
    path: '/monitoreo/monitoreo',
    title: 'Geo Visores',
    translateKey: 'nav.monitoreo.monitoreo',
    icon: '',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Ejecución',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2025',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2024',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2023',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Esc. riesgo 2023',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2022',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Esc. riesgo y PPRRD 2022',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Estudios inv 2022',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2021',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2020-2021',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2019',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
            ],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Indicadores',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Indicador GRD 2024',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Supervisión PPRRD',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
            ],
        },
        {
            key: 'monitoreo.monitoreo',
            path: '/monitoreo/monitoreo',
            title: 'Resultados ponderados',
            translateKey: 'nav.monitoreo.monitoreo',
            icon: '',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [],
            subMenu: [
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2024',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2020-2021',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2019',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2018',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
                {
                    key: 'monitoreo.monitoreo',
                    path: '/monitoreo/monitoreo',
                    title: 'Enagerd 2017',
                    translateKey: 'nav.monitoreo.monitoreo',
                    icon: '',
                    type: NAV_ITEM_TYPE_COLLAPSE,
                    authority: [],
                    subMenu: [],
                },
            ],
        },
    ],
};
export default navigationConfig;
