import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'gestionProcesos',
        path: '',
        title: 'DGP',
        translateKey: 'nav.gestionProcesos',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'gestionProcesos.lluviasAvisoTrimestral',
                path: '/gestion-procesos/lluviasAvisoTrimestral',
                title: 'LLUVIAS AVISO TRIMESTRAL',
                translateKey: 'nav.gestionProcesos.lluviasAvisoTrimestral',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.lluviasInformacionClimatica',
                path: '/gestion-procesos/lluviasInformacionClimatica',
                title: 'LLUVIAS INFORMACIÓN CLIMÁTICA',
                translateKey: 'nav.gestionProcesos.lluviasInformacionClimatica',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.bajasTempAvisoMeteorologico',
                path: '/gestion-procesos/bajasTempAvisoMeteorologico',
                title: 'BAJAS TEMP AVISO METEOROLÓGICO',
                translateKey: 'nav.gestionProcesos.bajasTempAvisoMeteorologico',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.bajasTempAvisoTrimestral',
                path: '/gestion-procesos/bajasTempAvisoTrimestral',
                title: 'BAJAS TEMP AVISO TRIMESTRAL',
                translateKey: 'nav.gestionProcesos.bajasTempAvisoTrimestral',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.bajasTempInformacionClimatica',
                path: '/gestion-procesos/bajasTempInformacionClimatica',
                title: 'BAJAS TEMP INFORMACIÓN CLIMÁTICA',
                translateKey: 'nav.gestionProcesos.bajasTempInformacionClimatica',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.incendiosForestalesNacional',
                path: '/gestion-procesos/incendiosForestalesNacional',
                title: 'INCENDIOS FORESTALES NACIONAL',
                translateKey: 'nav.gestionProcesos.incendiosForestalesNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.incendiosForestalesRegional',
                path: '/gestion-procesos/incendiosForestalesRegional',
                title: 'INCENDIOS FORESTALES REGIONAL',
                translateKey: 'nav.gestionProcesos.incendiosForestalesRegional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sismosTsunamiNacional',
                path: '/gestion-procesos/sismosTsunamiNacional',
                title: 'SISMOS TSUNAMI NACIONAL',
                translateKey: 'nav.gestionProcesos.sismosTsunamiNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sismosTsunamiOtrosAmbitos',
                path: '/gestion-procesos/sismosTsunamiOtrosAmbitos',
                title: 'SISMOS TSUNAMI OTROS ÁMBITOS',
                translateKey: 'nav.gestionProcesos.sismosTsunamiOtrosAmbitos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sequiasNacional',
                path: '/gestion-procesos/sequiasNacional',
                title: 'SEQUÍAS NACIONAL',
                translateKey: 'nav.gestionProcesos.sequiasNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sequiasDepartamental',
                path: '/gestion-procesos/sequiasDepartamental',
                title: 'SEQUÍAS DEPARTAMENTAL',
                translateKey: 'nav.gestionProcesos.sequiasDepartamental',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.volcanesNacional',
                path: '/gestion-procesos/volcanesNacional',
                title: 'VOLCANES NACIONAL',
                translateKey: 'nav.gestionProcesos.volcanesNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'fortalecimiento',
        path: '',
        title: 'DIFAT',
        translateKey: 'nav.fortalecimiento',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'fortalecimiento.capacitacion',
                path: '/fortalecimiento/capacitacion',
                title: 'Dashboard',
                translateKey: 'nav.fortalecimiento.capacitacion',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'monitoreo',
        path: '',
        title: 'Monitoreo, Seguimiento y Evaluación',
        translateKey: 'nav.monitoreo',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'monitoreo.seguimiento',
                path: '/monitoreo/seguimiento',
                title: 'Seguimiento',
                translateKey: 'nav.monitoreo.seguimiento',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'monitoreo.evaluacion',
                path: '/monitoreo/evaluacion',
                title: 'Evaluación de Resultados',
                translateKey: 'nav.monitoreo.evaluacion',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
