import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'pages',
        path: '',
        title: 'PAGES',
        translateKey: 'nav.pages',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [],
    },
    {
        key: 'gestionProcesos',
        path: '',
        title: 'DGP',
        translateKey: 'nav.gestionProcesos',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'gestionProcesos.lluviasAvisoTrimestral',
                path: '/gestion-procesos/lluviasAvisoTrimestral',
                title: 'LLuvias Aviso Trimestral',
                translateKey: 'nav.gestionProcesos.lluviasAvisoTrimestral',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.lluviasAvisoMeteorologico',
                path: '/gestion-procesos/lluviasAvisoMeteorologico',
                title: 'LLUVIAS AVISO METEOROLÓGICO',
                translateKey: 'nav.gestionProcesos.lluviasAvisoMeteorologico',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.lluviasInformacionClimatica',
                path: '/gestion-procesos/lluviasInformacionClimatica',
                title: 'LLUVIAS INFORMACIÓN CLIMÁTICA',
                translateKey: 'nav.gestionProcesos.lluviasInformacionClimatica',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.bajasTempAvisoMeteorologico',
                path: '/gestion-procesos/bajasTempAvisoMeteorologico',
                title: 'BAJAS TEMP AVISO METEOROLÓGICO',
                translateKey: 'nav.gestionProcesos.bajasTempAvisoMeteorologico',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.bajasTempAvisoTrimestral',
                path: '/gestion-procesos/bajasTempAvisoTrimestral',
                title: 'BAJAS TEMP AVISO TRIMESTRAL',
                translateKey: 'nav.gestionProcesos.bajasTempAvisoTrimestral',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.bajasTempInformacionClimatica',
                path: '/gestion-procesos/bajasTempInformacionClimatica',
                title: 'BAJAS TEMP INFORMACIÓN CLIMÁTICA',
                translateKey:
                    'nav.gestionProcesos.bajasTempInformacionClimatica',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.incendiosForestalesNacional',
                path: '/gestion-procesos/incendiosForestalesNacional',
                title: 'INCENDIOS FORESTALES NACIONAL',
                translateKey: 'nav.gestionProcesos.incendiosForestalesNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.incendiosForestalesRegional',
                path: '/gestion-procesos/incendiosForestalesRegional',
                title: 'INCENDIOS FORESTALES REGIONAL',
                translateKey: 'nav.gestionProcesos.incendiosForestalesRegional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sismosTsunamiNacional',
                path: '/gestion-procesos/sismosTsunamiNacional',
                title: 'SISMOS TSUNAMI NACIONAL',
                translateKey: 'nav.gestionProcesos.sismosTsunamiNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sismosTsunamiOtrosAmbitos',
                path: '/gestion-procesos/sismosTsunamiOtrosAmbitos',
                title: 'SISMOS TSUNAMI OTROS ÁMBITOS',
                translateKey: 'nav.gestionProcesos.sismosTsunamiOtrosAmbitos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sequiasNacional',
                path: '/gestion-procesos/sequiasNacional',
                title: 'SEQUÍAS NACIONAL',
                translateKey: 'nav.gestionProcesos.sequiasNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.sequiasDepartamental',
                path: '/gestion-procesos/sequiasDepartamental',
                title: 'SEQUÍAS DEPARTAMENTAL',
                translateKey: 'nav.gestionProcesos.sequiasDepartamental',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestionProcesos.volcanesNacional',
                path: '/gestion-procesos/volcanesNacional',
                title: 'VOLCANES NACIONAL',
                translateKey: 'nav.gestionProcesos.volcanesNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    // {
    //     key: 'fortalecimiento',
    //     path: '',
    //     title: 'DIFAT',
    //     translateKey: 'nav.fortalecimiento',
    //     icon: 'collapseMenu',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    // subMenu: [
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Resumen Instrumento Niv Nac',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Resumen Dpto Asist Tec Fortalec',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Fort Cap Cursos Bas y Espec',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Evaluadores de Riesgo Acred',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Fort Cap y Ambitos',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Riesgo por Fen Naturales',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Otras Asistencias Tec Nacional',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Concurso Buenas Practicas',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Concurso Buenas Practicas',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Fases del PPRD Nacional',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Instrumentos Especialistas Nacional',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Sesiones Espec PPRD Nivel Nac',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    //     {
    //         key: 'fortalecimiento.dashboard',
    //         path: '/fortalecimiento/dashboard',
    //         title: 'Entidades Asist Esp PPRD Nacional',
    //         translateKey: 'nav.fortalecimiento.dashboard',
    //         icon: '',
    //         type: NAV_ITEM_TYPE_ITEM,
    //         authority: [],
    //         subMenu: [],
    //     },
    // ],
    // },
    {
        key: 'dimse',
        path: '',
        title: 'DIFAT',
        translateKey: 'nav.dimse',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'fortalecimiento.resumenInstrumentoNivNac',
                path: '/fortalecimiento/resumenInstrumentoNivNac',
                title: 'Resumen Instrumento Niv Nac',
                translateKey: 'nav.fortalecimiento.resumenInstrumentoNivNac',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.resumenDptoAsistTecFortalec',
                path: '/fortalecimiento/resumenDptoAsistTecFortalec',
                title: 'Resumen Dpto Asist Tec Fortalec',
                translateKey: 'nav.fortalecimiento.resumenDptoAsistTecFortalec',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.fortCapCursosBasYEspec',
                path: '/fortalecimiento/fortCapCursosBasYEspec',
                title: 'Fort Cap Cursos Bas y Espec',
                translateKey: 'nav.fortalecimiento.fortCapCursosBasYEspec',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.pprdNivelNacional',
                path: '/fortalecimiento/pprdNivelNacional',
                title: 'Fort Cap Cursos Bas y Espec',
                translateKey: 'nav.fortalecimiento.pprdNivelNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.evaluadoresDeRiesgoAcred',
                path: '/fortalecimiento/evaluadoresDeRiesgoAcred',
                title: 'Evaluadores de Riesgo Acred',
                translateKey: 'nav.fortalecimiento.evaluadoresDeRiesgoAcred',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.fortCapYAmbitos',
                path: '/fortalecimiento/fortCapYAmbitos',
                title: 'Fort Cap y Ambitos',
                translateKey: 'nav.fortalecimiento.fortCapYAmbitos',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.riesgoPorFenNaturales',
                path: '/fortalecimiento/riesgoPorFenNaturales',
                title: 'Riesgo por Fen Naturales',
                translateKey: 'nav.fortalecimiento.riesgoPorFenNaturales',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.otrasAsistenciasTecNacional',
                path: '/fortalecimiento/otrasAsistenciasTecNacional',
                title: 'Otras Asistencias Tec Nacional',
                translateKey: 'nav.fortalecimiento.otrasAsistenciasTecNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.concursoBuenasPracticas',
                path: '/fortalecimiento/concursoBuenasPracticas',
                title: 'Concurso Buenas Practicas',
                translateKey: 'nav.fortalecimiento.concursoBuenasPracticas',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.fasesDelPprdNacional',
                path: '/fortalecimiento/fasesDelPprdNacional',
                title: 'Fases del PPRD Nacional',
                translateKey: 'nav.fortalecimiento.fasesDelPprdNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.instrumentosEspecialistasNacional',
                path: '/fortalecimiento/instrumentosEspecialistasNacional',
                title: 'Instrumentos Especialistas Nacional',
                translateKey:
                    'nav.fortalecimiento.instrumentosEspecialistasNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.sesionesEspecPprdNivelNac',
                path: '/fortalecimiento/sesionesEspecPprdNivelNac',
                title: 'Sesiones Espec PPRD Nivel Nac',
                translateKey: 'nav.fortalecimiento.sesionesEspecPprdNivelNac',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fortalecimiento.entidadesAsistEspPprdNacional',
                path: '/fortalecimiento/entidadesAsistEspPprdNacional',
                title: 'Entidades Asist Esp PPRD Nacional',
                translateKey:
                    'nav.fortalecimiento.entidadesAsistEspPprdNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'monitoreo',
        path: '',
        title: 'DIMSE',
        translateKey: 'nav.monitoreo',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'monitoreo.directorioNacional',
                path: '/monitoreo/directorioNacional',
                title: 'Directorio Nacional',
                translateKey: 'nav.monitoreo.directorioNacional',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'monitoreo.monitoreo',
                path: '/monitoreo/monitoreo',
                title: 'Monitoreo',
                translateKey: 'nav.monitoreo.monitoreo',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'monitoreo.seguimiento',
                path: '/monitoreo/seguimiento',
                title: 'Seguimiento',
                translateKey: 'nav.monitoreo.seguimiento',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'monitoreo.supervision',
                path: '/monitoreo/supervision',
                title: 'Supervisión',
                translateKey: 'nav.monitoreo.supervision',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'monitoreo.evaluacion',
                path: '/monitoreo/evaluacion',
                title: 'Evaluación',
                translateKey: 'nav.monitoreo.evaluacion',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
